# 채널 처리 함수

- 컬러 영상은 파란색(B), 녹색(G), 빨간색(R) 각기 독립적인 2차원 정보를 합쳐 놓은 배열이라고 정의 
- 파이썬에서는 넘파이 배열에 영상정보를 담을 수 있으며, 일련의 3개 원소로 하나의 컬러 화소가 구성되며, 화소 단위로 순회한다. 
- 컬러 배열을 분리하면 각 채널을 단일 채널 행렬로 구성할 수 있으며, 세부적인 영상처리에 이용할 수 있다 

- cv2.merge(mv[, dst]): 여러 개의 단일 채널 배열을 다채널 배열로 합성한다 
    - mv : 합성될 입력 배열 혹은 벡터, 합성될 단일 채널 배열들의 크기와 깊이가 동일해야 한다 
    - dst : 입력 배열과 같은 크기와 같은 깊이의 출력 배열

- cv2.split(m[, dst]): 다채널 배열을 여러 개의 단일 채널 배열로 분리한다 
    - m : 입력되는 다채널 배열
    - mv : 분리되어 반환되는 단일 채널 배열들의 벡터 

In [1]:
import numpy as np
import cv2


In [2]:
# numpy array이용해 단일 채널 3개 생성
ch0 = np.zeros((2, 4), np.uint8) + 10           # 0원소 행렬 선언 후 10 더하기
ch1 = np.ones((2, 4), np.uint8) * 20            # 1원소 행렬 선언 후 20 곱하기
ch2 = np.zeros((2, 4), np.uint8); ch2[:] = 30   # 0원소 행렬 선언 후 행렬원소값 30 지정


In [3]:
list_bgr = [ch0, ch1, ch2]                      # 단일 채널들을 모아 리스트 구성
merge_bgr = cv2.merge(list_bgr)                 # 채널 합성
split_bgr = cv2.split(merge_bgr)                # 채널 분리: 컬러영상--> 3채널 분리

In [4]:
print('split_bgr 행렬 형태 ', np.array(split_bgr).shape)
print('merge_bgr 행렬 형태', merge_bgr.shape)

split_bgr 행렬 형태  (3, 2, 4)
merge_bgr 행렬 형태 (2, 4, 3)


In [11]:
print("[ch0] = \n%s\n" % ch0)                     # 단일 채널 원소 출력
print("[ch1] = \n%s\n" % ch1)
print("[ch2] = \n%s" % ch2)

[ch0] = 
[[10 10 10 10]
 [10 10 10 10]]

[ch1] = 
[[20 20 20 20]
 [20 20 20 20]]

[ch2] = 
[[30 30 30 30]
 [30 30 30 30]]


In [8]:
print("[merge_bgr] = \n %s\n" % merge_bgr)       # 다중 채널 원소 출력

[merge_bgr] = 
 [[[10 20 30]
  [10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]
  [10 20 30]]]



In [12]:
print("[split_bgr[0]] =\n%s\n " % split_bgr[0])
print("[split_bgr[1]] =\n%s\n " % split_bgr[1])
print("[split_bgr[2]] =\n%s " % split_bgr[2])

[split_bgr[0]] =
[[10 10 10 10]
 [10 10 10 10]]
 
[split_bgr[1]] =
[[20 20 20 20]
 [20 20 20 20]]
 
[split_bgr[2]] =
[[30 30 30 30]
 [30 30 30 30]] 
