# 원소의 절댓값 연산

- cv2.absdiff(src1, src2[, dst]) : 두 배열간 각 원소간 차분 절댓값을 게산한다 
- cv2.convertScaleAbs(src[, dst[, alpha[, beta]]]) : 입력 배열의 각 원소에 alpha 만큼 배율을 곱하고 beta 만큼 더한 후에 절댓밧을 계산한 결과를 8비트 자료형으로 변환
    - alpha : 입력 배열의 각 원소에 곱해지는 스케일 팩터(scale factor)
    - beta : 스케일 된 값에 더해지는 델타 옵션 


In [2]:
import numpy as np, cv2

In [3]:
image1 = cv2.imread("img/abs_test1.jpg", cv2.IMREAD_GRAYSCALE) # 명암도 영상 읽기
image2 = cv2.imread("img/abs_test2.jpg", cv2.IMREAD_GRAYSCALE)
if image1 is None or image2 is None: raise Exception("영상 파일 읽기 오류 발생")

In [4]:
dif_img1 = cv2.subtract(image1, image2)                     # 차분 연산
dif_img2 = cv2.subtract(np.int16(image1), np.int16(image2)) # 음수 보전 위해
abs_dif1 = np.absolute(dif_img2).astype('uint8')
abs_dif2 = cv2.absdiff(image1, image2)              # 차분 절댓값 계산


In [5]:
x, y, w, h = 100, 100, 7, 3
print("[dif_img1(roi) uint8] = \n%s\n" % dif_img1[y:y+h, x:x+w])
print("[dif_img2(roi) int16]  = \n%s\n"  % dif_img2[y:y+h, x:x+w])
print("[abs_dif1(roi)] = \n%s\n" % abs_dif1[y:y+h, x:x+w])
print("[abs_dif2(roi)] = \n%s\n" % abs_dif2[y:y+h, x:x+w])


[dif_img1(roi) uint8] = 
[[ 0  0  0  0  9 12  7]
 [ 0  0  0  0  4  9  3]
 [ 0  0  0 15  0  4  0]]

[dif_img2(roi) int16]  = 
[[-100 -106  -80   -6    9   12    7]
 [-105 -109  -72   -4    4    9    3]
 [-106 -109  -58   15   -1    4    0]]

[abs_dif1(roi)] = 
[[100 106  80   6   9  12   7]
 [105 109  72   4   4   9   3]
 [106 109  58  15   1   4   0]]

[abs_dif2(roi)] = 
[[100 106  80   6   9  12   7]
 [105 109  72   4   4   9   3]
 [106 109  58  15   1   4   0]]



In [6]:
titles = ['image1', 'image2', 'dif_img1', 'abs_dif1','abs_dif2']
for title in titles:
    cv2.imshow(title, eval(title))
cv2.waitKey(0)

-1

![reulst](img/10_result.png)