# 원소의 최솟값과 최댓값

- cv2.min(src1, scr2[, dst]) : 두 입력 배열의 원소 간 비교하여 적은 값을 출력 배열로 반환
- cv2.max(src1, scr2[, dst]) : 두 입력 배열의 원소 간 비교하여 큰 값을 배열로 반환 
- cv2.minMaxLoc(src[, mask]) : 입력 배열에서 최솟값과 최댓값, 최솟값과 최댓값을 갖는 원소 위치를 반환 
    - scr : 입력 배열
    - minVal, maxVal : 최솟값, 최댓값
    - minLoc, maxLoc : 최솟값, 최댓값을 갖는 원소 위치(정수형 튜플)

In [1]:
import numpy as np, cv2

In [2]:
data = [10, 200, 5 , 7 ,  9,
        15, 35 , 60, 80, 170,
        100, 2 , 55, 37, 70]
m1 = np.reshape(data, (3, 5))   # 리스트를 행태변환하여 행렬 생성
m2 = np.full((3, 5), 50)              # 원소값 50인 행렬 생성

m_min = cv2.min(m1, 30)                  # 두 행렬 원소 간 최솟값을 행렬로 저장
m_max = cv2.max(m1, m2)                  # 두 행렬 최댓값 계산


In [4]:
## 행렬의 최솟값/최댓값과 그 좌표들을 반환
min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(m1)

print("[m1] = \n%s\n" % m1)
print("[m_min] = \n%s\n" % m_min)
print("[m_max] = \n%s\n" % m_max)


[m1] = 
[[ 10 200   5   7   9]
 [ 15  35  60  80 170]
 [100   2  55  37  70]]

[m_min] = 
[[10 30  5  7  9]
 [15 30 30 30 30]
 [30  2 30 30 30]]

[m_max] = 
[[ 50 200  50  50  50]
 [ 50  50  60  80 170]
 [100  50  55  50  70]]



In [5]:
# min_loc와 max_loc 좌표는 (y, x)이므로 행렬의 좌표 위차와 반대임
print("m1 행렬 최솟값 좌표 %s, 최솟값: %d" %(min_loc, min_val) )
print("m1 행렬 최댓값 좌표 %s, 최댓값: %d" %(max_loc, max_val) )

m1 행렬 최솟값 좌표 (1, 2), 최솟값: 2
m1 행렬 최댓값 좌표 (1, 0), 최댓값: 200
