# 행렬 원소 정렬

In [1]:
import numpy as np, cv2

In [2]:
m = np.random.randint(0,100, 15).reshape(3,5)           # 임의 난수 생성
# 행렬 원소 정렬
sort1 = cv2.sort(m, cv2.SORT_EVERY_ROW)                       # 행단위 오름차순
sort2 = cv2.sort(m, cv2.SORT_EVERY_COLUMN)                    # 열단위(세로) 오름차순
sort3 = cv2.sort(m, cv2.SORT_EVERY_ROW + cv2.SORT_DESCENDING) # 행단위(가로) 내림차순
sort4 = np.sort(m, axis=1)                                      # 세로축 정렬
sort5 = np.sort(m, axis=0)                                      # 가로축 정렬
sort6 = np.sort(m, axis=1)[:, ::-1]                             # 가로축 내림차순 정렬


In [3]:
titles= ['m','sort1','sort2','sort3','sort4','sort5', 'sort6']
for title in titles:
        print("[%s] = \n%s\n" %(title, eval(title)))


[m] = 
[[72  0  6 70 75]
 [90 45 53 80 26]
 [83 17 51 67 13]]

[sort1] = 
[[ 0  6 70 72 75]
 [26 45 53 80 90]
 [13 17 51 67 83]]

[sort2] = 
[[72  0  6 67 13]
 [83 17 51 70 26]
 [90 45 53 80 75]]

[sort3] = 
[[75 72 70  6  0]
 [90 80 53 45 26]
 [83 67 51 17 13]]

[sort4] = 
[[ 0  6 70 72 75]
 [26 45 53 80 90]
 [13 17 51 67 83]]

[sort5] = 
[[72  0  6 67 13]
 [83 17 51 70 26]
 [90 45 53 80 75]]

[sort6] = 
[[75 72 70  6  0]
 [90 80 53 45 26]
 [83 67 51 17 13]]

