# 정렬 인덱스 반환

In [1]:
import numpy as np, cv2

In [2]:
m = np.random.randint(0,100, 15).reshape(3,5)           # 임의 난수 생성

m_sort1 = cv2.sortIdx(m, cv2.SORT_EVERY_ROW)        # 행렬 원소의 원본 좌표
m_sort2 = cv2.sortIdx(m, cv2.SORT_EVERY_COLUMN)
m_sort3 = np.argsort(m, axis=0)                         # 세로축 정렬


In [3]:
print("[m1] = \n%s\n" % m)
print("[m_sort1] = \n%s\n" % m_sort1)
print("[m_sort2] = \n%s\n" % m_sort2)
print("[m_sort3] = \n%s\n" % m_sort3)


[m1] = 
[[10 31 46 87 84]
 [43 47 29 43 23]
 [61 35 76 45 66]]

[m_sort1] = 
[[0 1 2 4 3]
 [4 2 0 3 1]
 [1 3 0 4 2]]

[m_sort2] = 
[[0 0 1 1 1]
 [1 2 0 2 2]
 [2 1 2 0 0]]

[m_sort3] = 
[[0 0 1 1 1]
 [1 2 0 2 2]
 [2 1 2 0 0]]

