# 행렬 축소 연산

In [1]:
import numpy as np, cv2

In [2]:
m = np.random.rand(3,5) * 1000//10

reduce_sum = cv2.reduce(m, dim=0, rtype=cv2.REDUCE_SUM) # 0 - 열방향 축소
reduce_avg = cv2.reduce(m, dim=1, rtype=cv2.REDUCE_AVG) # 1 - 행방향 축소
reduce_max = cv2.reduce(m, dim=0, rtype=cv2.REDUCE_MAX)
reduce_min = cv2.reduce(m, dim=1, rtype=cv2.REDUCE_MIN)

In [3]:
print("[m1] = \n%s\n" %m)
print("[m_reduce_sum] =", reduce_sum.flatten())
print("[m_reduce_avg] =", reduce_avg.flatten())
print("[m_reduce_max] =", reduce_max.flatten())
print("[m_reduce_min] =", reduce_min.flatten())


[m1] = 
[[78. 19. 51. 55.  2.]
 [11. 44. 70. 71. 55.]
 [45. 77. 16. 63. 45.]]

[m_reduce_sum] = [134. 140. 137. 189. 102.]
[m_reduce_avg] = [41.  50.2 49.2]
[m_reduce_max] = [78. 77. 70. 71. 55.]
[m_reduce_min] = [ 2. 11. 16.]
