# 행렬 연산 함수

- cv2.gemm(src1, src2, alpha, src3, beta[, dst[, flags]]) : 일반화된 행렬 곱셈을 수행
    - scr1, src2 : 행렬 곱을 위한 두 입력 행렬(np.float32/np.float64형 2채널까지 가능)
    - alpha : 행렬 곱에 대한 가중치 
    - src3 : 행렬 곱에 더해지는 델타 행렬 
    - beta : src3 행렬에 곱해지는 가중치 
    - flags : 연산 플래그 - 옵션을 조합하여 입력 행렬들을 전치 

| 옵션 | 값 | 설명 |
|:------|:------|:------|
| cv2.GEMM_1_T | 1 | src1을 전치 |
| cv2.GEMM_2_T | 2 | src2을 전치 |
| cv2.GEMM_3_T | 4 | src3을 전치 |


- cv2.perspectiveTransform(src, m[, dst]) : 입력 베터들에 대해서 투영 (perspective) 변환 m을 수행
    - src : 좌표로 변환될 2채널 혹은 3채널의 부동 소수점 배열
    - dst : src 와 같은 크기와 타입의 출력 배열
    - m : 3x3 혹은 4x4 부동소수점의 투영 변환 행렬 

In [1]:
import numpy as np, cv2

In [2]:
src1 = np.array([1, 2, 3, 1, 2, 3], np.float32).reshape(2, 3) # 2x3 행렬 선언
src2 = np.array([1, 2, 3, 4, 5, 6], np.float32).reshape(2, 3)
src3 = np.array([1, 2, 1, 2, 1, 2], np.float32).reshape(3, 2) # 3x2 행렬 선언
alpha, beta = 1.0, 1.0

In [3]:
dst1 = cv2.gemm(src1, src2, alpha, None, beta, flags=cv2.GEMM_1_T)
dst2 = cv2.gemm(src1, src2, alpha, None, beta, flags=cv2.GEMM_2_T)
dst3 = cv2.gemm(src1, src3, alpha, None, beta)

In [4]:
titles = ['src1','src1','src1','dst1','dst2','dst3']
for title in titles:
    print("[%s] = \n%s\n" % (title, eval(title)))

[src1] = 
[[1. 2. 3.]
 [1. 2. 3.]]

[src1] = 
[[1. 2. 3.]
 [1. 2. 3.]]

[src1] = 
[[1. 2. 3.]
 [1. 2. 3.]]

[dst1] = 
[[ 5.  7.  9.]
 [10. 14. 18.]
 [15. 21. 27.]]

[dst2] = 
[[14. 32.]
 [14. 32.]]

[dst3] = 
[[ 6. 12.]
 [ 6. 12.]]

