# 역행렬의 계산 방법에 대한 옵션(flags) 값과 설명

- cv2.invert(src,[, dst[, flags]]) : 행렬의 역행렬을 계산한다 (입력 행렬이 정방 행렬이 아니면 의사 역행렬 계산)
    - src : M x N 크기의 부동 소수점 입력 행렬 
    - dst : src 와 크기와 타입이 같은 출력 행렬
    - flags : 역행렬의 게산 방법에 대한 플래그 


- cv2.solve(src1, src2[, dst[, flags]]) : 연립 방정식이나 최소자승 문제를 해결
    - src1 : 연립방적식의 개수 행렬
    - src2 : 연립방적식의 상수 행렬
    - dst : 출력 행렬
    - flags : 풀이 (역행렬 계산 플러그) 방법 

# flags 옵션의 역행렬의 계산 방법 

| 옵션 | 값 | 설명 |
|:------|:------|:------|
| cv2.DECOMP_LU | 0 | 가우시안 소거법으로 역행렬 계산 - 입력 행렬은 역행렬이 존재하는 정방행렬 |
| cv2.DECOMP_SVD | 1 | 특이치 분해 방법으로 역행렬 계산 - 입력 행렬이 정방행렬이 아닌 경우 의사 역행렬 계산 |
| cv2.DECOMP_CHOLESKY | 3 | 츌레스키(cholesky) 분해로 역행렬 계산 - 입력 행렬이 역행렬이 존재하는 정방행렬, 대칭행렬이며 양의 정부호 행렬 |


In [1]:
import numpy as np, cv2

In [2]:
data = [ 3, 0, 6, -3, 4, 2, -5,-1, 9]				    # 1차원 리스트 생성
m1 = np.array(data, np.float32).reshape(3,3)
m2 = np.array([36, 10, 28], np.float32)

In [3]:
ret, inv = cv2.invert(m1, cv2.DECOMP_LU)                # 역행렬 계산
if ret:
    dst1 = inv.dot(m2)                                  # numpy 제공 행렬곱 함수
    dst2 = cv2.gemm(inv, m2, 1, None, 1)                # OpenC 제공 행렬곱 함수
    ret, dst3 = cv2.solve(m1, m2, cv2.DECOMP_LU)        # 연립방정식 풀이

    print("[inv] = \n%s\n" % inv)
    print("[dst1] =", dst1.flatten())                   # 다행 1열 행렬을 한행에 표시
    print("[dst2] =", dst2.flatten())                   # 행렬을 벡터로 변환
    print("[dst3] =", dst3.flatten())                   # 행렬을 벡터로 변환
else:
    print("역행렬이 존재하지 않습니다.")

[inv] = 
[[ 0.15079366 -0.02380952 -0.0952381 ]
 [ 0.06746032  0.22619048 -0.0952381 ]
 [ 0.09126984  0.01190476  0.04761905]]

[dst1] = [2.5238097 2.0238094 4.7380953]
[dst2] = [2.5238097 2.0238097 4.7380953]
[dst3] = [2.5238094 2.0238094 4.7380953]


In [4]:
ret, inv = cv2.invert(m1, cv2.DECOMP_SVD)                # 역행렬 계산
if ret:
    dst1 = inv.dot(m2)                                  # numpy 제공 행렬곱 함수
    dst2 = cv2.gemm(inv, m2, 1, None, 1)                # OpenC 제공 행렬곱 함수
    ret, dst3 = cv2.solve(m1, m2, cv2.DECOMP_SVD)        # 연립방정식 풀이

    print("[inv] = \n%s\n" % inv)
    print("[dst1] =", dst1.flatten())                   # 다행 1열 행렬을 한행에 표시
    print("[dst2] =", dst2.flatten())                   # 행렬을 벡터로 변환
    print("[dst3] =", dst3.flatten())                   # 행렬을 벡터로 변환
else:
    print("역행렬이 존재하지 않습니다.")

[inv] = 
[[ 0.15079366 -0.02380952 -0.0952381 ]
 [ 0.06746032  0.22619048 -0.0952381 ]
 [ 0.09126984  0.01190476  0.04761905]]

[dst1] = [2.5238097 2.0238094 4.7380953]
[dst2] = [2.5238097 2.0238097 4.7380953]
[dst3] = [2.5238094 2.0238094 4.7380953]


In [5]:
ret, inv = cv2.invert(m1, cv2.DECOMP_CHOLESKY)                # 역행렬 계산
if ret:
    dst1 = inv.dot(m2)                                  # numpy 제공 행렬곱 함수
    dst2 = cv2.gemm(inv, m2, 1, None, 1)                # OpenC 제공 행렬곱 함수
    ret, dst3 = cv2.solve(m1, m2, cv2.DECOMP_CHOLESKY)        # 연립방정식 풀이

    print("[inv] = \n%s\n" % inv)
    print("[dst1] =", dst1.flatten())                   # 다행 1열 행렬을 한행에 표시
    print("[dst2] =", dst2.flatten())                   # 행렬을 벡터로 변환
    print("[dst3] =", dst3.flatten())                   # 행렬을 벡터로 변환
else:
    print("역행렬이 존재하지 않습니다.")

[inv] = 
[[ 0.15079366 -0.02380952 -0.0952381 ]
 [ 0.06746032  0.22619048 -0.0952381 ]
 [ 0.09126984  0.01190476  0.04761905]]

[dst1] = [2.5238097 2.0238094 4.7380953]
[dst2] = [2.5238097 2.0238097 4.7380953]
[dst3] = [2.5238094 2.0238094 4.7380953]
